/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_rotatingticket_yajd_util_zinnia_Recognizer */

#ifndef _Included_me_rotatingticket_yajd_util_zinnia_Recognizer
#define _Included_me_rotatingticket_yajd_util_zinnia_Recognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_rotatingticket_yajd_util_zinnia_Recognizer
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_rotatingticket_yajd_util_zinnia_Recognizer_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     me_rotatingticket_yajd_util_zinnia_Recognizer
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_me_rotatingticket_yajd_util_zinnia_Recognizer_create
  (JNIEnv *, jclass);

/*
 * Class:     me_rotatingticket_yajd_util_zinnia_Recognizer
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_me_rotatingticket_yajd_util_zinnia_Recognizer_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     me_rotatingticket_yajd_util_zinnia_Recognizer
 * Method:    classify
 * Signature: (Lme/rotatingticket/yajd/util/zinnia/Character;J)Lme/rotatingticket/yajd/util/zinnia/ResultSet;
 */
JNIEXPORT jobject JNICALL Java_me_rotatingticket_yajd_util_zinnia_Recognizer_classify
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     me_rotatingticket_yajd_util_zinnia_Recognizer
 * Method:    what
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_rotatingticket_yajd_util_zinnia_Recognizer_what
  (JNIEnv *, jobject);

/*
 * Class:     me_rotatingticket_yajd_util_zinnia_Recognizer
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_rotatingticket_yajd_util_zinnia_Recognizer_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class me_rotatingticket_yajd_util_zinnia_Character */

#ifndef _Included_me_rotatingticket_yajd_util_zinnia_Character
#define _Included_me_rotatingticket_yajd_util_zinnia_Character
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_rotatingticket_yajd_util_zinnia_Character
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_rotatingticket_yajd_util_zinnia_Character_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     me_rotatingticket_yajd_util_zinnia_Character
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_me_rotatingticket_yajd_util_zinnia_Character_create
  (JNIEnv *, jclass);

/*
 * Class:     me_rotatingticket_yajd_util_zinnia_Character
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_rotatingticket_yajd_util_zinnia_Character_clear
  (JNIEnv *, jobject);

/*
 * Class:     me_rotatingticket_yajd_util_zinnia_Character
 * Method:    setWidth
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_me_rotatingticket_yajd_util_zinnia_Character_setWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     me_rotatingticket_yajd_util_zinnia_Character
 * Method:    setHeight
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_me_rotatingticket_yajd_util_zinnia_Character_setHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     me_rotatingticket_yajd_util_zinnia_Character
 * Method:    draw
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_me_rotatingticket_yajd_util_zinnia_Character_draw
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     me_rotatingticket_yajd_util_zinnia_Character
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_rotatingticket_yajd_util_zinnia_Character_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class me_rotatingticket_yajd_util_zinnia_ResultSet */

#ifndef _Included_me_rotatingticket_yajd_util_zinnia_ResultSet
#define _Included_me_rotatingticket_yajd_util_zinnia_ResultSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_rotatingticket_yajd_util_zinnia_ResultSet
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_rotatingticket_yajd_util_zinnia_ResultSet_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     me_rotatingticket_yajd_util_zinnia_ResultSet
 * Method:    value
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_rotatingticket_yajd_util_zinnia_ResultSet_value
  (JNIEnv *, jobject, jlong);

/*
 * Class:     me_rotatingticket_yajd_util_zinnia_ResultSet
 * Method:    score
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_me_rotatingticket_yajd_util_zinnia_ResultSet_score
  (JNIEnv *, jobject, jlong);

/*
 * Class:     me_rotatingticket_yajd_util_zinnia_ResultSet
 * Method:    size
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_me_rotatingticket_yajd_util_zinnia_ResultSet_size
  (JNIEnv *, jobject);

/*
 * Class:     me_rotatingticket_yajd_util_zinnia_ResultSet
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_rotatingticket_yajd_util_zinnia_ResultSet_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
